import type { AccessoryDef } from "@/lib/types";

/** Auto-generated from extracted sticker PNGs */
export const EXTRACTED_ACCESSORIES: AccessoryDef[] = [
  {
    id: "disco-stars-01",
    label: "Disco star 01",
    src: "/assets/accessories/disco-stars-01.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-02",
    label: "Disco star 02",
    src: "/assets/accessories/disco-stars-02.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-03",
    label: "Disco star 03",
    src: "/assets/accessories/disco-stars-03.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-04",
    label: "Disco star 04",
    src: "/assets/accessories/disco-stars-04.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-05",
    label: "Disco star 05",
    src: "/assets/accessories/disco-stars-05.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-06",
    label: "Disco star 06",
    src: "/assets/accessories/disco-stars-06.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-07",
    label: "Disco star 07",
    src: "/assets/accessories/disco-stars-07.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-08",
    label: "Disco star 08",
    src: "/assets/accessories/disco-stars-08.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "disco-stars-09",
    label: "Disco star 09",
    src: "/assets/accessories/disco-stars-09.png",
    category: "party",
    defaultScale: 0.5,
  },
  {
    id: "drink-01",
    label: "Cocktail hand 01",
    src: "/assets/accessories/drink-01.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-02",
    label: "Cocktail hand 02",
    src: "/assets/accessories/drink-02.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-03",
    label: "Cocktail hand 03",
    src: "/assets/accessories/drink-03.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-04",
    label: "Cocktail hand 04",
    src: "/assets/accessories/drink-04.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-05",
    label: "Cocktail hand 05",
    src: "/assets/accessories/drink-05.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-06",
    label: "Cocktail hand 06",
    src: "/assets/accessories/drink-06.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-07",
    label: "Cocktail hand 07",
    src: "/assets/accessories/drink-07.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-08",
    label: "Cocktail hand 08",
    src: "/assets/accessories/drink-08.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-09",
    label: "Cocktail hand 09",
    src: "/assets/accessories/drink-09.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-10",
    label: "Cocktail hand 10",
    src: "/assets/accessories/drink-10.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "drink-11",
    label: "Cocktail hand 11",
    src: "/assets/accessories/drink-11.png",
    category: "party",
    defaultScale: 0.45,
  },
  {
    id: "holo-star-01",
    label: "Holo star 01",
    src: "/assets/accessories/holo-star-01.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-02",
    label: "Holo star 02",
    src: "/assets/accessories/holo-star-02.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-03",
    label: "Holo star 03",
    src: "/assets/accessories/holo-star-03.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-04",
    label: "Holo star 04",
    src: "/assets/accessories/holo-star-04.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-05",
    label: "Holo star 05",
    src: "/assets/accessories/holo-star-05.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-06",
    label: "Holo star 06",
    src: "/assets/accessories/holo-star-06.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-07",
    label: "Holo star 07",
    src: "/assets/accessories/holo-star-07.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-08",
    label: "Holo star 08",
    src: "/assets/accessories/holo-star-08.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-09",
    label: "Holo star 09",
    src: "/assets/accessories/holo-star-09.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-10",
    label: "Holo star 10",
    src: "/assets/accessories/holo-star-10.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-11",
    label: "Holo star 11",
    src: "/assets/accessories/holo-star-11.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-12",
    label: "Holo star 12",
    src: "/assets/accessories/holo-star-12.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-13",
    label: "Holo star 13",
    src: "/assets/accessories/holo-star-13.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-14",
    label: "Holo star 14",
    src: "/assets/accessories/holo-star-14.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-15",
    label: "Holo star 15",
    src: "/assets/accessories/holo-star-15.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-16",
    label: "Holo star 16",
    src: "/assets/accessories/holo-star-16.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-17",
    label: "Holo star 17",
    src: "/assets/accessories/holo-star-17.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-18",
    label: "Holo star 18",
    src: "/assets/accessories/holo-star-18.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-19",
    label: "Holo star 19",
    src: "/assets/accessories/holo-star-19.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-20",
    label: "Holo star 20",
    src: "/assets/accessories/holo-star-20.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-21",
    label: "Holo star 21",
    src: "/assets/accessories/holo-star-21.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "holo-star-22",
    label: "Holo star 22",
    src: "/assets/accessories/holo-star-22.png",
    category: "misc",
    defaultScale: 0.35,
  },
  {
    id: "martini-01",
    label: "Martini",
    src: "/assets/accessories/martini-01.png",
    category: "party",
    defaultScale: 0.55,
  },
  {
    id: "scrap-01",
    label: "Scrapbook sticker 01",
    src: "/assets/accessories/scrap-01.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-02",
    label: "Scrapbook sticker 02",
    src: "/assets/accessories/scrap-02.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-03",
    label: "Scrapbook sticker 03",
    src: "/assets/accessories/scrap-03.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-04",
    label: "Scrapbook sticker 04",
    src: "/assets/accessories/scrap-04.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-05",
    label: "Scrapbook sticker 05",
    src: "/assets/accessories/scrap-05.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-06",
    label: "Scrapbook sticker 06",
    src: "/assets/accessories/scrap-06.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-07",
    label: "Scrapbook sticker 07",
    src: "/assets/accessories/scrap-07.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-08",
    label: "Scrapbook sticker 08",
    src: "/assets/accessories/scrap-08.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-09",
    label: "Scrapbook sticker 09",
    src: "/assets/accessories/scrap-09.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-10",
    label: "Scrapbook sticker 10",
    src: "/assets/accessories/scrap-10.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-11",
    label: "Scrapbook sticker 11",
    src: "/assets/accessories/scrap-11.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-12",
    label: "Scrapbook sticker 12",
    src: "/assets/accessories/scrap-12.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-13",
    label: "Scrapbook sticker 13",
    src: "/assets/accessories/scrap-13.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-14",
    label: "Scrapbook sticker 14",
    src: "/assets/accessories/scrap-14.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-15",
    label: "Scrapbook sticker 15",
    src: "/assets/accessories/scrap-15.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "scrap-16",
    label: "Scrapbook sticker 16",
    src: "/assets/accessories/scrap-16.png",
    category: "misc",
    defaultScale: 0.42,
  },
  {
    id: "star-01",
    label: "Star sticker 01",
    src: "/assets/accessories/star-01.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-02",
    label: "Star sticker 02",
    src: "/assets/accessories/star-02.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-03",
    label: "Star sticker 03",
    src: "/assets/accessories/star-03.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-04",
    label: "Star sticker 04",
    src: "/assets/accessories/star-04.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-05",
    label: "Star sticker 05",
    src: "/assets/accessories/star-05.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-06",
    label: "Star sticker 06",
    src: "/assets/accessories/star-06.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-07",
    label: "Star sticker 07",
    src: "/assets/accessories/star-07.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-08",
    label: "Star sticker 08",
    src: "/assets/accessories/star-08.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-09",
    label: "Star sticker 09",
    src: "/assets/accessories/star-09.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-10",
    label: "Star sticker 10",
    src: "/assets/accessories/star-10.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-11",
    label: "Star sticker 11",
    src: "/assets/accessories/star-11.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-12",
    label: "Star sticker 12",
    src: "/assets/accessories/star-12.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-13",
    label: "Star sticker 13",
    src: "/assets/accessories/star-13.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-14",
    label: "Star sticker 14",
    src: "/assets/accessories/star-14.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "star-15",
    label: "Star sticker 15",
    src: "/assets/accessories/star-15.png",
    category: "misc",
    defaultScale: 0.38,
  },
  {
    id: "vintage-disco-ball-01",
    label: "Vintage disco ball",
    src: "/assets/accessories/vintage-disco-ball-01.png",
    category: "party",
    defaultScale: 0.55,
  },
  {
    id: "vintage-hand-01",
    label: "Vintage hand",
    src: "/assets/accessories/vintage-hand-01.png",
    category: "party",
    defaultScale: 0.5,
  },
];
